Lmod has detected the following error: The following module(s) are unknown:
"pytorch/1.4.0" "cuda/10.0.13"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "pytorch/1.4.0" "cuda/10.0.13"



Couldn't import umap
I'm counting gpu's:  1
Means I will train  1  models, with different random seeds
My Devices:  ['cuda:0']
Sampling dataset of 300000 training examples
  0%|          | 0/15 [00:00<?, ?trial/s, best loss=?]                                                      Testing hyperparameters:
  0%|          | 0/15 [00:00<?, ?trial/s, best loss=?]                                                      lr : 0.001764839303738569
  0%|          | 0/15 [00:00<?, ?trial/s, best loss=?]                                                      Trainingdataset:
  0%|          | 0/15 [00:04<?, ?trial/s, best loss=?]                                                      Dataset Crops
    Number of datapoints: 287858
    Root Location: data/Crops
    Reduce: average

  0%|          | 0/15 [00:04<?, ?trial/s, best loss=?]                                                      Using Evaluationdataset:
  0%|          | 0/15 [00:04<?, ?trial/s, best loss=?]                                                      Dataset Crops
    Number of datapoints: 55740
    Root Location: data/Crops
    Reduce: average

  0%|          | 0/15 [00:04<?, ?trial/s, best loss=?]2020-04-25 00:47:18.188095: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/lib:/cluster/apps/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/lib:/cluster/apps/gcc-4.8.5/jpeg-9b-psjvucpx7xwkflb3meatuo6ugdtapkex/lib:/cluster/apps/gcc-4.8.5/nccl-2.4.8-1-xpkpjc3dfz3c5knwctwl5vcut2ahfrwe/lib:/cluster/apps/gcc-4.8.5/cudnn-7.6.4-3ddmfyxxx2gkzhrra44ir3h3ls6yeuwe/lib64:/cluster/apps/gcc-4.8.5/cuda-10.1.243-7tq43deb5x4dbs4oe427w4zszno23q6r/extras/CUPTI/lib64:/cluster/apps/gcc-4.8.5/cuda-10.1.243-7tq43deb5x4dbs4oe427w4zszno23q6r/lib64:/cluster/apps/gcc-4.8.5/openblas-0.2.19-w25ydbabttcfa6g76gejjkthcm3xcuv3/lib:/cluster/apps/python/3.7.4/x86_64/lib64
2020-04-25 00:47:18.188404: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/lib:/cluster/apps/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/lib:/cluster/apps/gcc-4.8.5/jpeg-9b-psjvucpx7xwkflb3meatuo6ugdtapkex/lib:/cluster/apps/gcc-4.8.5/nccl-2.4.8-1-xpkpjc3dfz3c5knwctwl5vcut2ahfrwe/lib:/cluster/apps/gcc-4.8.5/cudnn-7.6.4-3ddmfyxxx2gkzhrra44ir3h3ls6yeuwe/lib64:/cluster/apps/gcc-4.8.5/cuda-10.1.243-7tq43deb5x4dbs4oe427w4zszno23q6r/extras/CUPTI/lib64:/cluster/apps/gcc-4.8.5/cuda-10.1.243-7tq43deb5x4dbs4oe427w4zszno23q6r/lib64:/cluster/apps/gcc-4.8.5/openblas-0.2.19-w25ydbabttcfa6g76gejjkthcm3xcuv3/lib:/cluster/apps/python/3.7.4/x86_64/lib64
2020-04-25 00:47:18.188424: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
                                                      runs/expID5526000_TRAINode_ns:300000_ba:400_ode-units:255_gru-uts:100_lats:70_rec-lay:2_solver:dopri5_seed:6001_optim:RMSprop_stackin:2
  0%|          | 0/15 [00:07<?, ?trial/s, best loss=?]run_models.py --niters 40 -n 300000 -validn 60000 -b 400 --lr 0.0084761 --ode-rnn --stacking 2 --ode-type linear --rnn-cell gru --ode-method dopri5 --random-seed 6001 --optimizer RMSprop --num-search 15 --num-seeds 1 --hparams lr

                                                      0.3272515249372085
  0%|          | 0/15 [9:30:04<?, ?trial/s, best loss=?]                                                         at step 
  0%|          | 0/15 [9:30:04<?, ?trial/s, best loss=?]                                                        95600
  0%|          | 0/15 [9:30:04<?, ?trial/s, best loss=?]                                                        {'loss': 0.6727484750627915, 'loss_variance': nan, 'status': 'ok', 'num_seeds': 1, 'best_acc': 0.3272515249372085, 'best_peak_step': 95600, 'best_steps': [95600]}
  0%|          | 0/15 [9:30:04<?, ?trial/s, best loss=?]  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/training.py:168: RuntimeWarning: invalid value encountered in true_divide
  var_test_acc = sum((abs(Test_acc - mean_test_acc)**2)/(num_seeds-1))

/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/training.py:171: RuntimeWarning: invalid value encountered in true_divide
  var_best_test_acc = sum((abs(Best_test_acc - mean_best_test_acc)**2)/(num_seeds-1))

/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/training.py:176: RuntimeWarning: invalid value encountered in true_divide
  var_train_acc = sum((abs(Train_acc - mean_train_acc)**2)/(num_seeds-1))

build_posterior_wrapper took 0.001461 seconds

TPE using 1/1 trials with best loss 0.672748

                                                                                         Testing hyperparameters:
  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         lr : 0.0005812710690299422
  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         Trainingdataset:
  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         Dataset Crops
    Number of datapoints: 287858
    Root Location: data/Crops
    Reduce: average

  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         Using Evaluationdataset:
  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         Dataset Crops
    Number of datapoints: 55740
    Root Location: data/Crops
    Reduce: average

  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]                                                                                         runs/expID6650000_TRAINode_ns:300000_ba:400_ode-units:255_gru-uts:100_lats:70_rec-lay:2_solver:dopri5_seed:6001_optim:RMSprop_stackin:2
  7%|▋         | 1/15 [9:30:04<133:01:07, 34204.85s/trial, best loss: 0.6727484750627915]run_models.py --niters 40 -n 300000 -validn 60000 -b 400 --lr 0.0084761 --ode-rnn --stacking 2 --ode-type linear --rnn-cell gru --ode-method dopri5 --random-seed 6001 --optimizer RMSprop --num-search 15 --num-seeds 1 --hparams lr

run_models.py --niters 40 -n 300000 -validn 60000 -b 400 --lr 0.0084761 --ode-rnn --stacking 2 --ode-type linear --rnn-cell gru --ode-method dopri5 --random-seed 6001 --optimizer RMSprop --num-search 15 --num-seeds 1 --hparams lr

job exception: 

job exception: 

  7%|▋         | 1/15 [9:31:29<133:20:58, 34289.87s/trial, best loss: 0.6727484750627915]
ODE-RNN  True
Classic-RNN:  False
Stacked layers:  2
ODE-type:  linear
RNN-cell:  gru
Weight-sharing:  False
defaut adapted LR's!!
Used Optimizer: RMSprop
Used Ode-Solver dopri5

---------------------------------------------------------------------------------------------------------------------------------------------
TRIAL PROTOCOL:
---------------------------------------------------------------------------------------------------------------------------------------------
Trial: 0001  |  #runs: 1  |  Mean Acc.: 32.725 %  |  Std: nan %  |  Best Acc.: 32.725 % (Peak: 95600 samples)  |  Hparams: {'lr': [0.001764839303738569]}  |
---------------------------------------------------------------------------------------------------------------------------------------------
Best configuration mean: 32.725 % (+-nan) (best run: 32.725 %) , with Hyperparmeters: {'lr': [0.001764839303738569]}
---------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "run_models.py", line 239, in <module>
    max_evals=args.num_search)
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/base.py", line 686, in fmin
    show_progressbar=show_progressbar,
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/fmin.py", line 509, in fmin
    rval.exhaust()
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/fmin.py", line 286, in run
    self.serial_evaluate()
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/fmin.py", line 165, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/hyperopt/base.py", line 894, in evaluate
    rval = self.fn(pyll_rval)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/training.py", line 157, in construct_and_train_model
    [Devices[0]]
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/training.py", line 268, in train_it
    train_res[i] = Model[i].compute_all_losses(batch_dict[i], n_traj_samples = 3, kl_coef = kl_coef)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/base_models.py", line 132, in compute_all_losses
    mode = batch_dict["mode"])
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/ode_rnn.py", line 244, in get_reconstruction
    input_sequence, truth_time_steps, run_backwards = False)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod_hparam/lib/encoder_decoder.py", line 462, in run_odernn
    assert(not torch.isnan(inc).any())
AssertionError
ODE-RNN  True
Classic-RNN:  False
Stacked layers:  2
ODE-type:  linear
RNN-cell:  gru
Weight-sharing:  False
defaut adapted LR's!!
Used Optimizer: RMSprop
Used Ode-Solver dopri5

---------------------------------------------------------------------------------------------------------------------------------------------
TRIAL PROTOCOL:
---------------------------------------------------------------------------------------------------------------------------------------------
Trial: 0001  |  #runs: 1  |  Mean Acc.: 32.725 %  |  Std: nan %  |  Best Acc.: 32.725 % (Peak: 95600 samples)  |  Hparams: {'lr': [0.001764839303738569]}  |
---------------------------------------------------------------------------------------------------------------------------------------------
Best configuration mean: 32.725 % (+-nan) (best run: 32.725 %) , with Hyperparmeters: {'lr': [0.001764839303738569]}
---------------------------------------------------------------------------------------------------------------------------------------------
