Lmod has detected the following error: The following module(s) are unknown:
"pytorch/1.4.0" "cuda/10.0.13"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "pytorch/1.4.0" "cuda/10.0.13"



Traceback (most recent call last):
  File "run_models.py", line 9, in <module>
    import matplotlib
  File "/cluster/apps/python/3.7.4/x86_64/lib64/python3.7/site-packages/matplotlib/__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "/cluster/apps/python/3.7.4/x86_64/lib64/python3.7/site-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    import numpy as np
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/numpy/lib/__init__.py", line 39, in <module>
    from .npyio import *
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 20, in <module>
    from ._iotools import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
KeyboardInterrupt
