Lmod has detected the following error: The following module(s) are unknown:
"pytorch/1.4.0" "cuda/10.0.13"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "pytorch/1.4.0" "cuda/10.0.13"



wandb: Starting wandb agent üïµÔ∏è
2020-07-08 15:09:35,330 - wandb.wandb_agent - INFO - Running runs: []
2020-07-08 15:09:35,664 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:09:35,665 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 10
2020-07-08 15:09:35,887 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python run_models.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=10
Traceback (most recent call last):
  File "run_models.py", line 10, in <module>
    import matplotlib
ImportError: No module named matplotlib
2020-07-08 15:09:40,901 - wandb.wandb_agent - INFO - Running runs: ['x08e5lip']
2020-07-08 15:09:40,902 - wandb.wandb_agent - INFO - Cleaning up finished run: x08e5lip
2020-07-08 15:09:41,224 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:09:41,225 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 20
2020-07-08 15:09:41,445 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python run_models.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=20
Traceback (most recent call last):
  File "run_models.py", line 10, in <module>
    import matplotlib
ImportError: No module named matplotlib
2020-07-08 15:09:46,456 - wandb.wandb_agent - INFO - Running runs: ['7i8eaazw']
2020-07-08 15:09:46,458 - wandb.wandb_agent - INFO - Cleaning up finished run: 7i8eaazw
2020-07-08 15:09:46,762 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:09:46,762 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 40
2020-07-08 15:09:46,981 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python run_models.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=40
Traceback (most recent call last):
  File "run_models.py", line 10, in <module>
    import matplotlib
ImportError: No module named matplotlib
2020-07-08 15:09:51,995 - wandb.wandb_agent - INFO - Running runs: ['aej2l3ki']
2020-07-08 15:09:51,996 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2020-07-08 15:09:51,996 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
